spring:
  data:
    mongodb:
      port: 32
      database: rips
      uri: "mongodb+srv://root:root@cluster0.bzow7vn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

jwt:
  secret: e3ff5f077839c1331b1d893a728246685cb7dba9e3a77bffe7d52eaccf660988